package pageObjects.ImpersonationPages;

import org.openqa.selenium.By;

public class ImpersonationElements {
    public static String photoPath= "C:\\Users\\omar.fawzy\\Documents\\screenshot of geidea marketing\\0 monthly fees.png";

    public static By paymentGatewayButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/ga-extended-menu-nav-item[4]/mat-list-item/span");
    public static By paymentGatewayButtonForOnboarding = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/ga-extended-menu-nav-item[3]/mat-list-item/span");
    public static By configurationButton = By.xpath("//*[text()='Configuration']");
    public static By instanceButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/div/ga-single-select/div/mat-icon");
    public static By liveInstanceButton = By.xpath("//*[text()=' Live instance ']");
    public static By gatewaySettingsButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/mat-tab-header/div[2]/div/div/div[2]");
    public static By merchantPublicKeyText = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[2]/div/ga-gateway-settings/div/form/mat-form-field[1]/div/div[1]/div/label/input");
    public static By gatewayAPIPasswordText = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[2]/div/ga-gateway-settings/div/form/mat-form-field[2]/div/div[1]/div[1]/label/input");
    public static By showPasswordButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[2]/div/ga-gateway-settings/div/form/mat-form-field[2]/div/div[1]/div[2]/button[2]/span[1]/mat-icon");
    public static By testInstanceButton = By.xpath("//*[text()=' Test instance ']");
    public static By testPaymentsCategoryButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/mat-tab-header/div[2]/div/div/div[11]");
    public static By rightArrowButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/mat-tab-header/div[3]");
    public static By testPaymentsButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[11]/div/ga-test-payment/div/form/div[2]/ga-button/button/span[1]/div/span");
    public static By toggleButton = By.xpath("/html/body/div[1]/div[2]/div/label/label");
    public static By merchantKeyTextField = By.xpath("/html/body/div[1]/div[3]/div[2]/div[1]/input");
    public static By APIPasswordTextField = By.xpath("/html/body/div[1]/div[3]/div[1]/div[1]/input");
    public static By amountTextField = By.xpath("/html/body/div[1]/div[3]/div[2]/div[2]/input");
    public static By purchaseButton = By.xpath("//*[text()='Purchase']");
    public static By meezaCardButton = By.xpath("/html/body/div[4]/div[1]/div[12]/div[2]/div/div[2]/div/div[1]");
    public static By nextButton = By.xpath("//*[text()='Next']");
    public static By meezaPhoneNumberTextField = By.xpath("/html/body/div[4]/div[1]/div[12]/div[2]/div/div[2]/div/div[2]/div[2]/input");
    public static By successMsg = By.xpath("//*[text()='Success']");
    public static By salesButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/ga-extended-menu-nav-item[5]");
    public static By transactionsButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/ga-extended-menu-nav-item[5]/mat-list-item/span/div/div[2]/span[1]");
    public static By geideaTestPageText = By.xpath("//*[text()='Geidea Test Page']");
    public static By orderIDText = By.xpath("/html/body/div[2]/div/div[2]/p[5]/span");
    public static By showReceiptChckBox = By.xpath("//*[@id=\"showReceipt\"]");
    public static By viewDetailsButton = By.xpath("//*[text()=' View details ']");
    public static By profileButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/ga-user-bar/div/ga-user-bar-desktop-content/div/div/ga-user-menu-button-content/button/ga-user-menu-button/button/span[1]/div");
    public static By exitImpersonationButton = By.xpath("//*[text()=' Exit impersonation ']");
    public static By orderIDOnTransactionText = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transactions-page/div[2]/ga-extended-transaction/div[2]/ga-extended-transaction-table/ga-table/div[2]/table/tbody/tr[1]/td[4]/ga-table-row-cell/div/div");
    public static By testModeButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transactions-page/div[1]/ga-toggle-switch/div/label/span");
    public static By lastTransactionRowButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transactions-page/div[2]/ga-extended-transaction/div[2]/ga-extended-transaction-table/ga-table/div[2]/table/tbody/tr[1]/td[1]");
    public static By amountOnTransactionText = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transactions-page/div[2]/ga-extended-transaction/div[2]/ga-extended-transaction-table/ga-table/div[2]/table/tbody/tr[1]/td[11]/ga-table-row-cell/div/div/span");
    public static By netAmountText = By.xpath("//*[text()='0 EGP']");
    public static By MIDText = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transaction-details-page/ga-extended-transaction-details/div[3]/span[1]/span");
    public static By originalAmountText = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transaction-details-page/ga-extended-transaction-details/ga-extended-online/div/span[1]/span");
    public static By grossAmountText = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transaction-details-page/ga-extended-transaction-details/ga-extended-online/div/span[3]/span");
    public static By transactionTypeText = By.xpath("//*[text()=' Pay ']");
    public static By transactionsDetailsText = By.xpath("//*[text()=' Transactions Details ']");
    public static By BNPLButton = By.xpath("/html/body/div[2]/div[1]/div[12]/div[2]/div/div[3]/label/span/label");
    public static By valUButton = By.xpath("/html/body/div[2]/div[1]/div[12]/div[2]/div/div[3]/div/div[1]/div[1]/label");
    public static By valUPhoneNumberTextField = By.xpath("/html/body/div[2]/div[1]/div[2]/div/div[1]/div[2]/div/div[2]/input");
    public static By downPaymentTextField = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[2]/div/div[2]/div[2]/input");
    public static By threeMonthsInstallmentButton = By.xpath("/html/body/div[2]/div[1]/div[2]/div/div[2]/div/div[2]/div[3]/div[1]");
    public static By payCashAtDeliveryButton = By.xpath("/html/body/div[2]/div[1]/div[2]/div/div[2]/div/div[2]/div[6]/div/div[2]/label/div");
    public static By otpTextField = By.xpath("//*[@id=\"geideaModalForm\"]/div[2]/div/div[3]/div/div[2]/div[1]/div/input[1]");
    public static By finalizePurchaseButton = By.xpath("//*[text()='Finalize purchase']");
    public static By paymentFrame = By.xpath("/html/body/iframe[2]");
    public static By nextOnValuPageButton  = By.xpath("/html/body/div[2]/div[1]/div[2]/div/div[1]/div[2]/button");
    public static By nextOnDownPaymentPageButton  = By.xpath("/html/body/div[2]/div[1]/div[2]/div/div[2]/div/div[2]/button");
    public static By thePurchaseSuccessfullMSG = By.xpath("//*[text()='   Your purchase with Valu has been confirmed   ']");
    public static By successMsgForValu = By.xpath("//*[@id=\"modal-title\"]");
    public static By valuLogoOnTransactionPage = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transaction-details-page/ga-extended-transaction-details/div[2]/div[1]/span[2]/mat-icon");
    public static By BNPLOrderIDOnTransactionPageTxt = By.xpath("//*[@id=\"cdk-accordion-child-6\"]/div/div/div/span[1]/span");
    public static By souhoolaButton = By.xpath("/html/body/div[2]/div[1]/div[12]/div[2]/div/div[3]/div/div[2]/div[1]/label");
    public static By souhoolaPhoneNumberTextField = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[1]/div/div[2]/div[1]/div[2]/input");
    public static By souhoolaPinTextField = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[1]/div/div[2]/div[2]/input");
    public static By nextOnSouhoolaPageButton  = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[1]/div/div[2]/div[3]/button");
    public static By payNowOnlineButton  = By.xpath("/html/body/div[2]/div[1]/div[2]/div/div[2]/div/div[2]/div[6]/div/div[1]/label/div");
    public static By debitOrCreditCardButton  = By.xpath("/html/body/div[2]/div[1]/div[12]/div[2]/div/div[1]/div[1]/label");
    public static By NextOnSelectPaymentMethodPageButton  = By.xpath("/html/body/div[2]/div[1]/div[12]/div[2]/button");
    public static By cardNumberTextField  = By.xpath("/html/body/div[2]/div[1]/div[14]/div[2]/div/div/div/div[1]/input");
    public static By expiryDateTextField  = By.xpath("/html/body/div[2]/div[1]/div[14]/div[2]/div/div/div/div[2]/div[1]/input");
    public static By cvvTextField  = By.xpath("/html/body/div[2]/div[1]/div[14]/div[2]/div/div/div/div[2]/div[2]/input");
    public static By nameOnCardTextField  = By.xpath("/html/body/div[2]/div[1]/div[14]/div[2]/div/div/div/div[3]/input");
    public static By payOnSouhoolaPageButton  = By.xpath("/html/body/div[2]/div[1]/div[17]/button");
    public static By submitOnDSButton  = By.xpath("/html/body/div/div/div[3]/center/form/table/tbody/tr[4]/td/input");
    public static By DSFrame = By.xpath("/html/body/div[4]/div[2]/iframe");
    public static By OTPFrame = By.xpath("/html/body/iframe[2]");
    public static By PBLButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/cdk-virtual-scroll-viewport/div[1]/ga-extended-menu-nav-item[10]/mat-list-item/span/div/div/div[2]/button");
    public static By quickPayLinkButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/cdk-virtual-scroll-viewport/div[1]/ga-extended-menu-nav-item[10]/div/div[1]/span");
    public static By addNewCustomerButton = By.xpath("//*[text()=' Find or Add New Customer ']");
    public static By addCustomerButton = By.xpath("//*[text()=' Add  ']");
    public static By customerNamePBLTextField = By.xpath("/html/body/div[2]/div[3]/div/mat-dialog-container/ga-quick-pay-link-dialog/div/form/div[2]/mat-form-field[1]/div/div[1]/div/label/input");
    public static By customerEmailPBLTextField = By.xpath("/html/body/div[2]/div[3]/div/mat-dialog-container/ga-quick-pay-link-dialog/div/form/div[2]/mat-form-field[4]/div/div[1]/div/label/input");
    public static By PBLAmountTextField = By.xpath("/html/body/div[2]/div[3]/div/mat-dialog-container/ga-quick-pay-link-dialog/div/form/mat-form-field[1]/div/div[1]/div/ga-select-input/div/div[1]/input");
    public static By createAndSendPBLButton = By.xpath("/html/body/div[2]/div[3]/div/mat-dialog-container/ga-quick-pay-link-dialog/div/form/div[3]/div[2]/ga-button/button");
    public static By expandButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/ga-extended-menu-nav-button/div/div/button/span[1]/mat-icon");
    public static By sideBarFrame = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list");
public static By searchFindCustomerQuickPBLTextField = By.xpath("/html/body/div[2]/div[7]/div/ga-select-panel/ga-select-field/div");
    public static By selectedCustomerText = By.xpath("//*[@id=\"cdk-overlay-7\"]/ga-select-panel/ga-select-option-list/cdk-virtual-scroll-viewport/div[1]/ga-select-option[1]/div/div");
    public static By sixMonthsInstallmentSouhoolaButton = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[2]/div/div[2]/div[5]/div[1]/div[1]");
    public static By nextDownPaymentPageButton = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[2]/div/div[2]/button");
    public static By cashAtDeliverySouhoolaButton = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[3]/div/div[2]/div[2]/div/div[2]/label/div");
    public static By proceedSouhoolaButton = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[3]/div/div[2]/div[3]/button");
    public static By finalizePurchaseSouhoolaButton = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[4]/div/div[2]/button");
    public static By otpSouhoolaTextField = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[4]/div/div[2]/div[1]/div/input[1]");
    public static By payNowOnlineSouhoolaButton = By.xpath("/html/body/div[2]/div[1]/div[4]/div/div[3]/div/div[2]/div[2]/div/div[1]/label/div");
    public static By submitOnDSSouhoolaButton  = By.xpath("/html/body/div/div/div[3]/center/form/table/tbody/tr[4]/td/input");
    public static By creditOrDebitCardButton  = By.xpath("/html/body/div[2]/div[1]/div[12]/div[2]/div/div[1]/div[1]/label");
    public static By orderIDDebitOrCreditOnTransactionPageTxt = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transaction-details-page/ga-extended-transaction-details/div[3]/span[5]/span");
    public static By orderIDOnTransactionPageTxt = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transactions-page/div[2]/ga-extended-transaction/div[2]/ga-extended-transaction-table/ga-table/div[2]/table/tbody/tr[1]/td[4]/ga-table-row-cell/div/div");
    public static By staticPayLinkButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/cdk-virtual-scroll-viewport/div[1]/ga-extended-menu-nav-item[10]/div/div[4]");
    public static By createStaticPayLinkButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-invoice-layout/div/ga-animated-outlet/div/ga-pay-link-dashboard-page/div[2]/ga-button/button");
    public static By staticPayLinkTitleTextField = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-invoice-layout/div/ga-animated-outlet/div/ga-pay-link-create-page/form/ga-pay-link-details-form/div/div[2]/div[1]/mat-form-field/div/div[1]/div/label/input");
    public static By itemDescriptionStaticPayLinkTitleTextField = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-invoice-layout/div/ga-animated-outlet/div/ga-pay-link-create-page/form/ga-pay-link-item-form/div/div/div[1]/mat-form-field/div/div[1]/div/label/input");
    public static By unitPriceStaticPayLinkTitleTextField = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-invoice-layout/div/ga-animated-outlet/div/ga-pay-link-create-page/form/ga-pay-link-item-form/div/div/div[2]/mat-form-field/div/div[1]/div/label/input");
    public static By createButtonForStaticPayLink = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-invoice-layout/div/ga-animated-outlet/div/ga-pay-link-create-page/form/div[3]/ga-button[2]/button");
    public static By actionButtonForStaticPayLink = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-invoice-layout/div/ga-animated-outlet/div/ga-pay-link-dashboard-page/ga-table/div[2]/table/tbody/tr[1]/td[8]/ga-table-row-cell/div/div/ga-actions-menu-button/button");
    public static By viewDetailsButtonForStaticPayLink = By.xpath("//*[text()=' View details ']");
    public static By payLinkButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-invoice-layout/div/ga-animated-outlet/div/ga-pay-link-details-page/div[1]/div[2]/ga-copy-field/div/div/div/a");
    public static By customerNameOnPayLinkPageTitleTextField = By.xpath("/html/body/ga-root/div/ga-pay-link-page/div/div/ga-pay-link-panel[1]/div/form/ga-pay-link-form/div/mat-form-field[1]/div/div[1]/div/label/input");
    public static By customerEmailOnPayLinkPageTitleTextField = By.xpath("/html/body/ga-root/div/ga-pay-link-page/div/div/ga-pay-link-panel[1]/div/form/ga-pay-link-form/div/mat-form-field[2]/div/div[1]/div/label/input");
    public static By payButtonOnPaylinkPage = By.xpath("/html/body/ga-root/div/ga-pay-link-page/div/div/ga-pay-link-panel[1]/div/form/ga-button/button");
    public static By paylinkNumberText = By.xpath("/html/body/ga-root/div/ga-pay-link-page/div/div/ga-pay-link-panel[2]/div/ga-pay-link-item/span");
    public static By customerNameOnPayLinkPageText = By.xpath("/html/body/ga-root/div/ga-pay-link-page/div/div/div/div/span");
    public static By totalAmountOnPayLinkPageText = By.xpath("/html/body/ga-root/div/ga-pay-link-page/div/div/ga-pay-link-panel[2]/div/ga-pay-link-item/div[4]/span[2]");
    public static By convertLanguageButtonOnPayLinkPage = By.xpath("//*[@id=\"mat-select-value-1\"]/span/mat-select-trigger/mat-icon");
    public static By englishLanguageButtonOnPayLinkPage = By.xpath("/html/body/div[3]/div[2]/div/div/div/mat-option[1]");
    public static By staticPaylinkPaymentFrame = By.xpath("/html/body/iframe");
    public static By debitOrCreditOnPaylinkPageButton = By.xpath("/html/body/div[2]/div[1]/div[12]/div[2]/div/div[1]/div[1]/label");
    public static By payOnPaylinkPageButton = By.xpath("/html/body/ga-root/div/ga-e-invoice-page/div/div/pay-einvoice/form/div/div[3]/button");
    public static By orderIDOnStaticPaylinkReceiptText = By.xpath("/html/body/ga-root/div/ga-receipt-page/main/div[2]/section[2]/div[1]/span[2]");
    public static By paymentLinkNumberOnStaticPaylinkReceiptText = By.xpath("/html/body/ga-root/div/ga-receipt-page/main/div[2]/section[2]/div[2]/span[2]");
    public static By paidByNameOnStaticPaylinkReceiptText = By.xpath("/html/body/ga-root/div/ga-receipt-page/main/div[2]/section[3]/div/div/span[1]");
    public static By paidByEmailOnStaticPaylinkReceiptText = By.xpath("/html/body/ga-root/div/ga-receipt-page/main/div[2]/section[3]/div/div/span[2]");
    public static By grandAmountOnStaticPaylinkReceiptText = By.xpath("/html/body/ga-root/div/ga-receipt-page/main/div[2]/section[6]/ga-receipt-totals/div[2]/div/span[2]");
    public static By managementButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/ga-extended-menu-nav-item[7]/mat-list-item/span");
    public static By businessesButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/ga-extended-menu-nav/div/ga-extended-menu-nav-sidebar/mat-sidenav-container/mat-sidenav/div/div/mat-nav-list/ga-extended-menu-nav-item[7]/mat-list-item/span/div/div[2]/span[1]");
    public static By businessNameButton = By.xpath("//*[text()=' 1 ']");
    public static By editBusinessButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-business/div/div/div[1]/div/div/ga-button/button");
    public static By attachFileNIDButton = By.xpath("//*[@id=\"cdk-accordion-child-0\"]/div/ga-business-information-enhanced/div/form/div[2]/div/ga-file-list-improved/ga-button/button");
    public static By attachFileCommercialRegButton = By.xpath("//*[@id=\"cdk-accordion-child-0\"]/div/ga-business-information-enhanced/div/form/div[5]/div/ga-file-list-improved/ga-button/button");
    public static By saveChangesButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-business/div/div[2]/div[2]/form/div/div/ga-save-button/ga-button/button");
    public static By GSDKSettingsButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/mat-tab-header/div[2]/div/div/div[4]");
    public static By TIDTextField = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[4]/div/ga-gsdk-settings/div/form/mat-form-field[1]/div/div[1]/div/label/input");
    public static By MIDTextField = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[4]/div/ga-gsdk-settings/div/form/mat-form-field[2]/div/div[1]/div/label/input");
    public static By saveChangesPGWConfigurationsButton = By.xpath("//*[text()=' Save changes ']");
    public static By businessNameVerifiedButton = By.xpath("//*[text()=' Verified ']");
    public static By merchantWebsiteTextField = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[1]/div/ga-merchant-details/div/form/mat-form-field[2]/div/div[1]/div/label/input");
    public static By secretKeyButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-gateway-layout/div/ga-animated-outlet/div/ga-configuration-hub-page/div/mat-tab-group/div/mat-tab-body[4]/div/ga-gsdk-settings/div/form/mat-form-field[3]/div/div[1]/div[1]/label/input");
    public static By ToggleToFederateTransactionsToGSDKButton = By.xpath("//*[@id=\"mat-tab-content-1-3\"]/div/ga-gsdk-settings/div/form/div[1]/ga-toggle-switch/div/label/input");
    public static By refundButton = By.xpath("//*[text()=' Refund ']");
    public static By selectPartialRefundButton = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transaction-details-page/ga-extended-transaction-details/div[2]/div[2]/div/ga-select-button/div/button[2]");
    public static By partialRefundButton = By.xpath("//*[text()=' Partial Refund ']");
    public static By fullRefundInitiatedTxtMsg = By.xpath("/html/body/ga-root/div/ga-merchant-portal-layout/div/div/div/div/ga-animated-outlet/div/ga-transactions-layout/div/ga-animated-outlet/div/ga-transaction-details-page/ga-extended-transaction-details/div[2]/div[2]/span");
    public static By refundAmountTextField = By.xpath("/html/body/div[2]/div[10]/div/mat-dialog-container/ga-partial-refund-dialog/form/div[1]/mat-form-field/div/div[1]/div/label/input");
    public static By confirmToPartialRefundButton = By.xpath("//*[text()=' Confirm ']");
    public static By partialRefundInitiatedTxtMsg = By.xpath("//*[text()=' Paid - Partial Refund Initiated - PARTIAL Refund INITIATED ']");
    public static By valuDownPaymentTextField = By.xpath("/html/body/div[2]/div[1]/div[2]/div/div[2]/div/div[2]/div[2]/div[1]/input");
    public static By CallbackURLTextField = By.xpath("/html/body/div[1]/div[3]/div[3]/div[2]/input");
    public static By paymentOperationTextField = By.xpath("/html/body/div[1]/div[3]/div[5]/div[2]/input");
    public static By voidButton = By.xpath("//*[text()=' Void ']");
    public static By voidedButton = By.xpath("//*[text()=' Voided ']");
    public static By captureButton = By.xpath("//*[text()=' Capture ']");
    public static By capturedButton = By.xpath("//*[text()=' Captured ']");
    public static By tokenPaymentButton = By.xpath("/html/body/div[1]/div[3]/div[31]/div[2]");
    public static By tokenIDTextField = By.xpath("/html/body/div[1]/div[3]/div[32]/div/div[2]/input");
    public static By closeButton = By.xpath("//*[text()='Close']");
    public static By cvvOfTokenizedTextField  = By.xpath("/html/body/div[2]/div[1]/div[2]/div[1]/div[3]/div/input");
    public static By DSFrameOfTokenized = By.xpath("/html/body/div[5]/div[2]/iframe");
}
